apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgCtgOZ5fN9T4Zp6D0gO+98nTX1tyuwU/BdpulSHWR1n5WVRq9/J7GcLgSMVMfok/x5MA7rZs6DfVeFvZHxotSSc+bhR4ooqiQVJprLs8u+0jw1hzVAgvyt/vnPEVMyvKpZ9cClIOdUHP0bgu0TOyjTbtqDHfW+mp2pxCDEC73TZzLMg2XnTYYa6v4cCvGgnP4+a5y6c/2RuQPGzS2uTRVyBjqOr/YdOVgP6Y9C7q5h24vdJSpPEaf3oqDJX1blcrGMn4+KO+hJsSa8pqWdJkPPB0hMPK3LSz2CuEQ4QFwIwjpGRmxAdCL+fOH4I2aCsDaub34Vg/ojIAV43ffEuW3iISdaDIwetn0tREsEt6tSSi81XCl8VPFDuViAcmIu43vBD6OZFDAdKKXbwm3JgASJk+XCJlObpfpTJtAG3onBINWNRU7M0WwCZoscFIPZf3eiFeYBms56poB7i7bhKxPdsuue0c3PqLERsnrJLLnIOlZ5DCIhgMIApf3cPZvTbXe2RMNpyM+PzB9JUwqI3rDbhXf5K1MZPcF2B6FDJxkaWUsM8I7W6z9S/ilhvP23D4HhYh1LT1x0BzXMAJNsMEwK5yZ8irj9/u2pNgp9DOkRSD9/egkvTWTrFaWAApPTxjLom4xHhEH3IaeZGvW1lpbOaP43uf3zpYEWRznrpb2WPJpWbPoSKyFiwnTSK8Uq38YDYU9K4nuvtOWaWVfCzPDjHAjoBUQ==
    username: AgAWp+ZVDS9nflMVhR1iYt74sxF2VEp0EYD/6B/897Ql1uVeKsJBtKjNsZYRwxmJvGXkAGNRTuUlXsL+fiuLGqvL0mcU0Rpf6AgKqwQZyGGYpxHfn1mwnyQAMrgqarCQvVrH1TdxoQ1zcb/43i2a4smDMwps5uHoFiiMn+t3KBZHBcvOR6Je9Nr9CdnyU254ySvx3YqNDP7mJWFz1QXJlXDTynV84StAFAFauJstpf4rVjKmaWaGjaxEjh5RSOt7bSEt4lHarzCBDM7BBtKgmqHPWCG80U26mQfO56NvBnJElBNLlMCqDBshgCvlBBo0kpmk1au+MKoVK1xigZ79/eZEnVuHwkGBwHvLGc0wMTSPvx/ET60YQf3e8dF8ltm0sWNFxgVQKW5J2au7CCt144IrXk1cU12Wwty5wgZ+4Bm6lGyIevOw7aG+6ABGS8oSOpldDJr//RMoEdAbgybDQOETmzk9RoO1+Yf6mWUFzgvwV38RHYngMcVUPBNLohDQ9na/8C/Kn6x+2V8ad3FbME7rjl26RFSwxQD+QzltY3FUAwhAuYPPGKZbW5TXwnuDD4swZMV0NClGq72XH8s7R2YPPjFpdnMZakNgSP69X3jkqkMHh8dTssw9JKaiLdjiMoOCOJrEebGyTPVG7KLpHQ3G4Ss1rI+OA3q/z9bLH18zpmiEwtTz8bwdPHyWkB+TZe8hE9taHA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: argocd
    type: Opaque

