apiVersion: apps/v1
kind: Deployment
metadata:
  name: stiletto-harbor-registry
spec:
  template:
    spec:
      volumes:
        - name: registry-htpasswd
          secret:
            secretName: harbor-secret