apiVersion: v1
data:
  statusbadge.enabled: 'true'
  users.anonymous.enabled: 'true'
  policy.default: role:readonly
  kustomize.buildOptions: --enable-helm
kind: ConfigMap
metadata:
  name: argocd-cm

