apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  admin.enabled: 'false'
  users.anonymous.enabled: 'true'
  policy.default: role:readonly
  accounts.vanchaxy: apiKey, login
  statusbadge.enabled: 'true'
  kustomize.buildOptions: --enable-helm
  repositories: |
    - url: https://registry.ivanchenko.io/library/
      type: helm
      name: harbor
      usernameSecret:
        name: harbor-registry
        key: username
      passwordSecret:
        name: harbor-registry
        key: password
