apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/master-app.yaml
  - base/argo-cd.yaml
  - base/cert-manager.yaml
  - base/external-dns.yaml
  - base/monitoring.yaml
  - base/ingress-nginx.yaml
  - base/metallb.yaml
  - base/sealed-secrets.yaml
