apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: factorio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: factorio
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/factorio
    repoURL: https://github.com/vanchaxy/cluster
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true