apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/drone-secret.yaml

helmCharts:
  - name: drone
    namespace: drone
    releaseName: silex
    version: 0.6.1
    repo: https://charts.drone.io
    valuesInline:
      env:
        DRONE_SERVER_HOST: drone.ivanchenko.io
        DRONE_SERVER_PROTO: https
        DRONE_USER_FILTER: vanchaxy

      extraSecretNamesForEnvFrom:
        - drone-secret

      ingress:
        enabled: true

        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"

        hosts:
          - host: drone.ivanchenko.io
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: drone-tls
            hosts:
              - drone.ivanchenko.io

  - name: drone-runner-kube
    namespace: drone
    releaseName: silex
    version: 0.1.10
    repo: https://charts.drone.io
    valuesInline:
      env:
        DRONE_NAMESPACE_DEFAULT: drone

      extraSecretNamesForEnvFrom:
        - drone-secret

      ingress:
        enabled: true

        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"

        hosts:
          - host: drone-runner.ivanchenko.io
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: drone-tls
            hosts:
              - drone-runner.ivanchenko.io