st-reborn:
  existingSecret: "pass-secret"

  config:
    Gameplay:
      uDifficulty: 3

  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: production
      metallb.universe.tf/address-pool: metallb-pool
