apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: openebs
    namespace: openebs
    releaseName: silex
    version: 3.3.1
    repo: https://openebs.github.io/charts
    includeCRDs: true

patches:
  - target:
      version: storage.k8s.io/v1
      kind: StorageClass
      name: openebs-hostpath
    patch: |-
      - op: add
        path: /metadata/annotations/storageclass.kubernetes.io/is-default-class
        value: true