apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/local-hostpath-sc.yaml

helmCharts:
  - name: openebs
    namespace: openebs
    releaseName: silex
    version: 3.3.1
    repo: https://openebs.github.io/charts
    includeCRDs: true