apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: grafana
    namespace: monitoring
    releaseName: silex
    version: 6.35.0
    repo: https://grafana.github.io/helm-charts
    valuesInline:
      persistence:
        enabled: true
        size: 5Gi

      ingress:
        enabled: true

        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"

        hosts:
          - grafana.ivanchenko.io
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.ivanchenko.io

      testFramework:
        enabled: false
      rbac:
        pspEnabled: false

  - name: prometheus
    namespace: monitoring
    version: 15.12.0
    repo: https://prometheus-community.github.io/helm-charts
    valuesInline:
      alertmanager:
        enabled: false
      server:
        securityContext:
          fsGroup: 65534
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
