apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: sealed-secrets
    namespace: sealed-secrets
    version: 2.6.1
    repo: https://bitnami-labs.github.io/sealed-secrets
    includeCRDs: true