apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/argocd-server-ingress.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patchesStrategicMerge:
  - overlays/argocd-cm.yaml
  - overlays/argocd-rbac-cm.yaml

patchesJson6902:
  - path: overlays/argocd-server-deploy-command.yaml
    target:
      group: apps
      kind: Deployment
      name: argocd-server
      version: v1

namespace: argocd
