apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: harbor
    namespace: harbor
    releaseName: silex
    version: 1.9.3
    repo: https://helm.goharbor.io
    valuesInline:
      expose:
        ingress:
          hosts:
            core: harbor.ivanchenko.io
            notary: notary.ivanchenko.io
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      externalURL: https://harbor.ivanchenko.io
