apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/harbor-secret.yaml

helmCharts:
  - name: harbor
    namespace: harbor
    releaseName: stiletto
    version: 1.10.0
    repo: https://helm.goharbor.io
    valuesInline:
      externalURL: https://harbor.ivanchenko.io

      expose:
        type: ingress

        ingress:
          hosts:
            core: harbor.ivanchenko.io

          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/ssl-passthrough: "true"

      registry:
        credentials:
          username: "vanchaxy"
          existingSecret: "harbor-secret"

      existingSecretSecretKey: "harbor-secret"

      redis:
        external:
          existingSecret: "harbor-secret"

      trivy:
        enabled: false

      notary:
        enabled: false

patches:
  - path: overlays/registry-dpl-secret.yaml