apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: harbor
    namespace: harbor
    releaseName: silex
    version: 15.2.1
    repo: https://charts.bitnami.com/bitnami
    valuesInline:
      externalURL: https://harbor.ivanchenko.io
      exposureType: ingress
      ingress:
        core:
          hostname: harbor.ivanchenko.io
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/ssl-passthrough: "true"
          tls: true
      notary:
        enabled: false