apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secret
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgCo22XB6J+CIhe120LU9YoKjTpQrT40dWgKmiizToHjHDkxNY/v45HvfiJE9JQ++Wc2aEV5jXlVeEzwdM28jieiMSouaiIeZpak+XDSyHaRFwOwREu8tU+7LeQ+OM9SBz76JDdDiundTHe+bmk1MAk0MOH5X9Aa6psiTMQX99nEuDCJAddPABM9cAXsAbNF8yPdpqhxeAw2RGRjapBfs1XR+UW+1jVbQ5wOcgrn/FldwSPvnyzbA4zSztuvOT/m+7b3Fjc03x+07oVZRV/A1Dj5HQKNgWiTPNktX3f4cr+uTDxRYXS8cKvY6TkvLwWQBB+ghVOAA9djnFQynfcoqxMlnL2IgQHVMjv4mLnmZV+gAeHnZfxD5pHKGd3GWDofZt1FQH6FZpjJ6csIvVkpm+aDS9R8w2PXJCR9c7LIiDnQwX18lyG3gCToGnsHb+mgdl7cd1OJV5vXX24GdTD12c2uByckH2YlMF2ahKxDdk5w23DZJsiJfWXEIS2HkGdirVzHuDKBKS4zFa38jYeqrI2JYjytrh2LZo3wCujWXUFqqPrGxlMez6DTVJnf/QVO8HJWHMrK5wo+qS7I482Xy28pHAHrih84IggV0Cc+edjypL9yj78Vo9bjTJGJPW+2uFCrLagQuPbO4yi3G5hHxP+a/G/quiHFv0mxjrwC42s4xkk70CJklHlZAedF4s2ADeJBvx8sITsdPBJRHv/TqoOr+tv7ymL5NrjfgEw0C6MdzjeEd+jtvoAN
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: external-dns-secret
      namespace: external-dns

