apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/metallb-ns.yaml
  - base/metallb-pool.yaml
  - base/metallb-l2.yaml

helmCharts:
  - name: metallb
    namespace: metallb
    version: 4.1.1
    repo: https://charts.bitnami.com/bitnami
