apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: ingress-nginx
    namespace: ingress-nginx
    releaseName: silex
    version: 4.2.3
    repo: https://kubernetes.github.io/ingress-nginx
    valuesInline:
      annotations:
        metallb.universe.tf/address-pool: production-public-ips
