apiVersion: v2

name: apps
description: Parent helm chart for subtitles-player

type: application
version: 0.1.1
appVersion: "0.0.1"

dependencies:
  - name: subtitles-player
    repository: oci://registry.ivanchenko.io/library
    version: 0.1.1