subtitles-player:
  image:
    tag: "main-c111c461"
  imagePullSecrets:
    - name: regcred

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"

    hosts:
      - host: subtitles.ivanchenko.io
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: subtitles-tls
        hosts:
          - subtitles.ivanchenko.io