subtitles-player:
  image:
    tag: "main-89502e47"
  imagePullSecrets:
    - name: regcred

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"

    hosts:
      - subtitles.ivanchenko.io
    tls:
      - secretName: subtitles-tls
        hosts:
          - subtitles.ivanchenko.io