factorio:
  
  image:
    tag: 1.1.70
  service:
    main:
      enabled: true
      type: LoadBalancer
      externalTrafficPolicy: Cluster
      annotations:
        metallb.universe.tf/allow-shared-ip: production
        metallb.universe.tf/address-pool: metallb-pool
      ports:
        factorio-game:
          port: 34201
          protocol: UDP
          targetPort: 34197
        factorio-rcon:
          enabled: true
          port: 27015
          protocol: TCP
          targetPort: 27015
