apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/letsencrypt-issuer.yaml

helmCharts:
  - name: cert-manager
    namespace: cert-manager
    releaseName: silex
    version: v1.9.1
    repo: https://charts.jetstack.io
    valuesInline:
      installCRDs: true